Infinite scroll v3
dannydeezy/nosft pull request #74
Opened 2023-03-17 01:40 UTC by topether21

2023-03-20 21:20 UTC, Uthpala commented
@topether21 I think you will have to implement the sorting in the frontend. If not when the user triggers a sort we will have to fetch all the inscriptions again for that order. So its best to do the sorting in the frontend.

2023-03-20 22:44 UTC, topether21 commented
@andredevjs @Uthpala I enable filters and sort.

2023-03-21 19:58 UTC, Uthpala commented on src/hooks/use-ordinals.js
> +const axios = require("axios");
Why are we importing this the old way, 
```suggestion
import axios from 'axios'
```

2023-03-21 20:47 UTC, topether21 commented
I made the PR to main. Updating to use develop.

2023-03-21 21:45 UTC, Uthpala commented
Okay i just finished reviewing this. All is good to me. But unfortunately i cannot test every functionality to confirm its working 100% 

I tested filtering and sorting and inscription fetching and they are working well. 

Can someone please confirm other functionality like sending an ordinal is working so we can merge this.

2023-03-22 01:43 UTC, andredevjs commented
https://github.com/dannydeezy/nosft/pull/73 is merged. please update your branch with main, since you might have conflicts.

2023-03-22 02:03 UTC, topether21 commented
Very big screens are not triggering on scroll. Debugging...

<img width="513" alt="image" src="https://user-images.githubusercontent.com/126987350/226782839-042f4a6f-4c9f-4b5b-a60a-9b9f4248f6d0.png">

2023-03-22 17:47 UTC, Uthpala commented on src/utils/utxos.js
I think you can delete this file right ?

2023-03-22 21:53 UTC, Uthpala approved these changes

2023-03-24 13:25 UTC, andredevjs requested changes
@topether21 on load, it is adding the new inscriptions on top, but it should add them at the end!, just like FB or IG, or Pinterest with their posts. It also be good, if we don't have to scroll all the way down to load more inscriptions, that should happen opportunistically by loading them before the user reaches the end, that improves user experience by not having the user to wait for those inscriptions.

2023-03-24 13:26 UTC, andredevjs commented on package.json
> +        "lodash": "^4.17.21",
do we need the whole package?

2023-03-27 18:16 UTC, topether21 commented
<img width="928" alt="image" src="https://user-images.githubusercontent.com/126987350/228030083-669caf1c-ea7c-4a0a-8e23-7f193541f01b.png">

https://nosft.xyz/api/inscriptions/bc1p6hsehjafcdzzht5shm4qmm3w2aspwlh843w5r9s33ejhhwesy9qss2hxhp?offset=0&limit=5

@andredevjs here we are missing txid, and vout from the new API so we need to add them.
For example it has missing data on Send modal.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/126987350/228030567-e37263dd-9409-41e6-8474-0e17d99fc8f8.png">

2023-03-29 14:17 UTC, andredevjs approved these changes

2023-03-29 14:17 UTC, merged